
import { supabase } from '@/lib/customSupabaseClient';

export const login = async (email, password) => {
  try {
    const { data, error } = await supabase.auth.signInWithPassword({
      email,
      password,
    });

    if (error) throw error;
    return { user: data.user, session: data.session, error: null };
  } catch (error) {
    return { user: null, session: null, error: error.message };
  }
};

export const register = async (userData) => {
  try {
    // 1. Sign up with Supabase Auth
    const { data: authData, error: authError } = await supabase.auth.signUp({
      email: userData.email,
      password: userData.password,
      options: {
        data: {
          full_name: userData.name,
        }
      }
    });

    if (authError) throw authError;

    // 2. Create user profile in public.users table
    // We use the ID generated by Supabase Auth to link the records
    if (authData.user) {
      const { error: profileError } = await supabase
        .from('users')
        .upsert([{
          id: authData.user.id,
          email: userData.email,
          name: userData.name,
          phone: userData.phone,
          cpf: userData.cpf,
          bairro: userData.bairro,
          cep: userData.cep,
          cidade: userData.cidade,
          estado: userData.estado,
          role: 'user', // Default role
          created_at: new Date().toISOString(),
          updated_at: new Date().toISOString()
        }]);

      if (profileError) {
        // If profile creation fails, we should technically warn the user
        // but the auth account is already created.
        console.error('Error creating user profile:', profileError);
        throw new Error('Conta criada, mas houve um erro ao salvar o perfil.');
      }
    }

    return { user: authData.user, session: authData.session, error: null };
  } catch (error) {
    return { user: null, session: null, error: error.message };
  }
};

export const logout = async () => {
  try {
    const { error } = await supabase.auth.signOut();
    if (error) throw error;
    return { error: null };
  } catch (error) {
    return { error: error.message };
  }
};

export const getCurrentUser = async () => {
  const { data: { user }, error } = await supabase.auth.getUser();
  if (error) return { user: null, error: error.message };
  return { user, error: null };
};

export const updateUserProfile = async (userId, updates) => {
  try {
    const { data, error } = await supabase
      .from('users')
      .update({
        ...updates,
        updated_at: new Date().toISOString()
      })
      .eq('id', userId)
      .select()
      .single();

    if (error) throw error;
    return { user: data, error: null };
  } catch (error) {
    return { error: error.message };
  }
};
